[build]
  publish = "."  # Use "." if your HTML files (index.html, etc.) are in the root directory
  command = ""   # Leave empty since you're not using a static site generator like Hugo or Next.js

[[plugins]]
  package = "netlify-plugin-sitemap"

  [plugins.inputs]
    baseUrl = "https://scholargo.netlify.app"
    prettyURLs = true
