backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "scholarships"
    label: "Scholarships"
    folder: "scholarships"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      
