backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://scholargo.netlify.app
display_url: https://scholargo.netlify.app
logo_url: /assets/logo1.png
locale: "en"
publish_mode: editorial_workflow
editor:
  preview: true

collections:
  - name: "scholarships"
    label: "Scholarships"
    folder: "posts/scholarships"
    create: true
    slug: "{{slug}}"
    preview_path: "post.html?post={{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Slug", name: "slug", widget: "string", hint: "Leave blank to auto-generate" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Program Type", name: "category", widget: "select", options: ["BS", "MPhil", "PhD", "Fellowship"], required: true }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Deadline", name: "deadline", widget: "datetime", required: false }
      - { label: "External Link", name: "link", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
          - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
          - { label: "Canonical URL", name: "canonical_url", widget: "string", required: false }

  - name: "education"
    label: "Education"
    folder: "posts/education"
    create: true
    slug: "{{slug}}"
    preview_path: "post.html?post={{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Topic Type", name: "category", widget: "select", options: ["Course", "Guide", "Tutorial"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
          - { label: "Meta Description", name: "meta_description", widget: "text", required: false }

  - name: "technology"
    label: "Technology"
    folder: "posts/technology"
    create: true
    slug: "{{slug}}"
    preview_path: "post.html?post={{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tag Type", name: "category", widget: "select", options: ["Update", "Tool", "News"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
          - { label: "Meta Description", name: "meta_description", widget: "text", required: false }

  - name: "pages"
    label: "Static Pages"
    files:
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Privacy"
        name: "privacy"
        file: "privacy-policy.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
