backend:
  name: git-gateway
  repo: WebsiteGuy01/scholargo-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://scholargo.netlify.app
logo_url: /assets/logo1.png

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Scholarships", "Technology", "Education"]}
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Site Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}

      - label: "Privacy Policy"
        name: "privacy"
        file: "privacy-policy.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
