backend:
  name: git-gateway
  repo: WebsiteGuy01/scholargo-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://scholargo.netlify.app
logo_url: /assets/logo1.png

collections:
  - name: "scholarships"
    label: "Scholarships"
    folder: "posts/scholarships"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{date}}"
    preview_path: "scholarships/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["BS", "MPhil", "Fellowship"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "education"
    label: "Education"
    folder: "posts/education"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{date}}"
    preview_path: "education/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Course", "Tutorial", "Guide"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "technology"
    label: "Technology"
    folder: "posts/technology"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{date}}"
    preview_path: "technology/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Update", "Innovation", "Tool"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Site Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}

      - label: "Privacy Policy"
        name: "privacy"
        file: "privacy-policy.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}

      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}

# Optional config enhancements
publish_mode: editorial_workflow
locale: 'en'
show_preview_links: true

# Media Library Options
display_url: https://scholargo.netlify.app
editor:
  preview: true