backend:
  name: git-gateway
  branch: main

site_url: https://scholargo.netlify.app
display_url: https://scholargo.netlify.app
logo_url: /assets/logo1.png
locale: 'en'
publish_mode: editorial_workflow
show_preview_links: true

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

editor:
  preview: true

collections:
  - name: "scholarships"
    label: "Scholarships"
    folder: "posts/scholarships"
    create: true
    slug: "{{fields.title}}"
    summary: "{{title}} | {{category}} | {{date}}"
    preview_path: "post.html?post={{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false, hint: "Leave blank to auto-generate" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["BS", "MPhil", "Fellowship"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Deadline", name: "deadline", widget: "datetime", required: false }
      - { label: "Expire Date", name: "expire_date", widget: "datetime", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Reading Time (min)", name: "reading_time", widget: "number", required: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "Canonical URL", name: "canonical_url", widget: "string", required: false }
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "technology"
    label: "Technology"
    folder: "posts/technology"
    create: true
    slug: "{{fields.title}}"
    preview_path: "post.html?post={{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Update", "AI", "Tool", "Trend"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "education"
    label: "Education"
    folder: "posts/education"
    create: true
    slug: "{{fields.title}}"
    preview_path: "post.html?post={{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "select", options: ["Course", "Tutorial", "Guide", "MOOC"] }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "authors"
    label: "Authors"
    folder: "authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Photo", name: "photo", widget: "image", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }

  - name: "pages"
    label: "Static Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Privacy Policy"
        name: "privacy"
        file: "privacy-policy.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
